version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-7-39-178.compute-1.amazonaws.com
            port: '5432'
            database: d9iq0g8ro00h38
            ssl: true
            user: ygsvtwizedgkdt
            password: 4690387ecc033818fb3bc68fce99beeaa8769b47b20fccf72c48605c3ac0a85e
            migrations: true
